name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04              # pin runner to 22.04 so Playwright deps install cleanly
    steps:
      #1  Check out repo
      - uses: actions/checkout@v4

      #2 Pull submodule with the Flask demo
      - name: Init submodules
        run: git submodule update --init --recursive

      #3 Set up Python 3.12
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      #4 Install Python deps and Playwright browsers
      - run: pip install -r requirements.txt
      - run: playwright install --with-deps

      #5 Export login credentials from GitHub Secrets
      - name: Set credentials
        run: |
          echo "FT_USER=${{ secrets.FT_USER }}" >> $GITHUB_ENV
          echo "FT_PASS=${{ secrets.FT_PASS }}" >> $GITHUB_ENV

      #6 install the app’s requirements launching
      - run: pip install -r app/requirements.txt      # NEW: Flask, SQLAlchemy, etc.

      # 6 Launch Finance-Tracker Flask server in the background
      - name: Launch Finance-Tracker
        run: |
          python scripts/seed_user.py          # seed DB first
          cd app                               # enter submodule
          python app.py &                      # start server
          sleep 3

      #7 Run Playwright test suite
      - name: Run Playwright test suite
        run: pytest --capture=tee-sys -v    # streams Rich output