name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt
      - run: playwright install --with-deps

      # debug step
      - name: Show workspace
        run: |
          echo "### workspace content ###"
          ls -R
          echo "### end workspace ###"

      # export secrets as env vars for pytest
      - name: Set credentials
        run: |
          echo "FT_USER=${{ secrets.FT_USER }}" >> $GITHUB_ENV
          echo "FT_PASS=${{ secrets.FT_PASS }}" >> $GITHUB_ENV
      
      # start the Finance-Tracker app in the background
      - name: Launch Finance-Tracker
        run: |
          python app/app.py &
          sleep 3   # give server time to bind on :5000

      - run: pytest -q