name: CI
on:
  push:
    paths-ignore:
      - 'README.md' # not running the CI when README.md is the only thing pushed to master
  pull_request:
  workflow_dispatch:  # enables manual "Run workflow"

jobs:
  test:
    runs-on: ubuntu-22.04              # pin runner to 22.04 so Playwright deps install cleanly
    permissions:
      contents: write
    steps:
      #1  Check out repo
      - uses: actions/checkout@v4

      #2 Pull submodule with the Flask demo
      - name: Init submodules
        run: git submodule update --init --recursive

      #3 Set up Python 3.12
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      #4 Install Python deps and Playwright browsers
      - run: pip install -r requirements.txt
      - run: playwright install --with-deps

      #5 Export login credentials from GitHub Secrets
      - name: Set credentials
        run: |
          echo "FT_USER=${{ secrets.FT_USER }}" >> $GITHUB_ENV
          echo "FT_PASS=${{ secrets.FT_PASS }}" >> $GITHUB_ENV

      #6 install the app’s requirements launching
      - run: pip install -r app/requirements.txt      # NEW: Flask, SQLAlchemy, etc.

      #7 Launch Finance-Tracker Flask server in the background
      - name: Launch Finance-Tracker
        run: |
          python scripts/seed_user.py          # seed DB first
          cd app                               # enter submodule
          python app.py &                      # start server
          sleep 3

      #8 runs the catalog script on every pull‑request regenerating the selector_registry.json, commits it if changed amd pushes in same PR context (skips if no diff)
      - name: Update selector registry
        run: |
          python scripts/catalog_selectors.py
          if ! git diff --quiet selector_registry.json ; then
            git config user.name  "ci‑bot"
            git config user.email "ci@github"
            git add selector_registry.json
            git commit -m "ci: auto‑update selector registry"
            # push only if we have a token (own repo, not fork PR)
            if [ "${{ github.repository_owner }}" = "narekp" ]; then
              git push origin HEAD:${{ github.ref_name }}
            fi
          fi

      #9 Run Playwright test suite
      - name: Run Playwright test suite
        run: pytest --capture=tee-sys -v    # streams Rich output